export default function Head() {
  return (
    <>
      <title>DevEx - Where Developers Exchange</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />

      {/* TODO: Change the favicon to a custom logo, also... make a custom logo */}
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
